// flow-typed signature: b4e959e6d88c5a62bf607bb0b23cf382
// flow-typed version: <<STUB>>/react-bottom-scroll-listener_v1.3.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bottom-scroll-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bottom-scroll-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.cjs' {
  declare module.exports: any;
}

declare module 'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.esm' {
  declare module.exports: any;
}

declare module 'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.umd' {
  declare module.exports: any;
}

declare module 'react-bottom-scroll-listener/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.cjs.js' {
  declare module.exports: $Exports<'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.cjs'>;
}
declare module 'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.esm.js' {
  declare module.exports: $Exports<'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.esm'>;
}
declare module 'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.umd.js' {
  declare module.exports: $Exports<'react-bottom-scroll-listener/dist/react-bottom-scroll-listener.umd'>;
}
declare module 'react-bottom-scroll-listener/lib/index.js' {
  declare module.exports: $Exports<'react-bottom-scroll-listener/lib/index'>;
}
