// flow-typed signature: 51b395e6b95de047c409406ef19e2734
// flow-typed version: <<STUB>>/firebase/app_v5/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase/app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase/app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/app/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'firebase/app/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/app/dist/index.cjs.js' {
  declare module.exports: $Exports<'firebase/app/dist/index.cjs'>;
}
declare module 'firebase/app/dist/index.esm.js' {
  declare module.exports: $Exports<'firebase/app/dist/index.esm'>;
}
