extends: airbnb
parser: babel-eslint
rules:
  jsx-a11y/anchor-is-valid:
   - error
   - components:
      - Link
     specialLink:
      - to
  no-console: 1
  react/forbid-prop-types: 0
  # import/no-extraneous-dependencies: 0
  # import/no-unresolved: 0
  # jsx-a11y/click-events-have-key-events: 0
  # no-alert: 0
  # no-underscore-dangle: 0
  # no-unused-expressions: 0
  # object-curly-newline: 0
  # prettier/prettier: 2
  # quote-props: 0
  # react/jsx-no-target-blank: 0
  # react/no-array-index-key: 1
  # react/no-danger: 0
  # react/react-in-jsx-scope: 0

  # 以下、Prettierとバッティングを防ぐための設定
  arrow-parens: 0
  function-paren-newline: 0
  linebreak-style: 0

env:
  mocha: true
  jest: true

# stop no-undef warning about global variables.
globals:
  document: true
  window: true
  graphql: true
  localStorage: true
  fetch: true