export default {
  GET_OR_CREATE_USER_INFO_SUCCESS: 'GET_OR_CREATE_USER_INFO_SUCCESS',
  GET_OR_CREATE_USER_INFO_FAIL: 'GET_OR_CREATE_USER_INFO_FAIL',

  FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
  FETCH_USER_INFO_FAIL: 'FETCH_USER_INFO_FAIL',

  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAIL: 'UPDATE_USER_INFO_FAIL',

  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAIL: 'DELETE_USER_FAIL',

  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_OUT_USER_FAIL: 'SIGN_OUT_USER_FAIL',

  FETCH_ALL_POSTS_SUCCESS: 'FETCH_ALL_POSTS_SUCCESS',
  FETCH_ALL_POSTS_FAIL: 'FETCH_ALL_POSTS_FAIL',

  FETCH_POST_START: 'FETCH_POST_START',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POST_FAIL: 'FETCH_POST_FAIL',

  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAIL: 'CREATE_POST_FAIL',

  EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
  EDIT_POST_FAIL: 'EDIT_POST_FAIL',

  FETCH_MY_POSTS_SUCCESS: 'FETCH_MY_POSTS_SUCCESS',
  FETCH_MY_POSTS_FAIL: 'FETCH_MY_POSTS_FAIL',

  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAIL: 'DELETE_POST_FAIL',

  DELETE_POSTS_SUCCESS: 'DELETE_POSTS_SUCCESS',
  DELETE_POSTS_FAIL: 'DELETE_POSTS_FAIL',

  INCREASE_LIMIT_COUNT_OF_GRID: 'INCREASE_LIMIT_COUNT_OF_GRID',

  SELECT_MY_POSTS: 'SELECT_MY_POSTS',
  SELECT_MY_POSTS_ALL: 'SELECT_MY_POSTS_ALL',
  SELECT_MY_POSTS_RESET: 'SELECT_MY_POSTS_RESET',

  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAIL: 'CREATE_COMMENT_FAIL',

  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAIL: 'DELETE_COMMENT_FAIL',

  TOGGLE_LIKE_SUCCESS: 'TOGGLE_LIKE_SUCCESS',
  TOGGLE_LIKE_FAIL: 'TOGGLE_LIKE_FAIL',

  REDUCE_SNACKBAR_QUEUE: 'REDUCE_SNACKBAR_QUEUE',

  ADD_SNACKBAR_QUEUE: 'ADD_SNACKBAR_QUEUE',

  START_PROGRESS: 'START_PROGRESS',
  FINISH_PROGRESS: 'FINISH_PROGRESS',
};
