export default {
  FETCH_ALL_POSTS_SUCCESS: 'FETCH_ALL_POSTS_SUCCESS',
  FETCH_ALL_POSTS_FAIL: 'FETCH_ALL_POSTS_FAIL',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAIL: 'CREATE_POST_FAIL',
};
