export default {
  INIT_AUTH: 'INIT_AUTH',
  INIT_AUTH_FAIL: 'INIT_AUTH_FAIL',
  INIT_AUTH_USER_HAS_CREDENTIAL: 'INIT_AUTH_USER_HAS_CREDENTIAL',
  INIT_AUTH_USER_HAS_NO_CREDENTIAL: 'INIT_AUTH_USER_HAS_NO_CREDENTIAL',

  GET_OR_CREATE_USER_INFO: 'GET_OR_CREATE_USER_INFO',
  GET_OR_CREATE_USER_INFO_SUCCESS: 'GET_OR_CREATE_USER_INFO_SUCCESS',
  GET_OR_CREATE_USER_INFO_FAIL: 'GET_OR_CREATE_USER_INFO_FAIL',

  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAIL: 'UPDATE_USER_INFO_FAIL',

  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAIL: 'DELETE_USER_FAIL',

  SIGN_IN_WITH_GOOGLE: 'SIGN_IN_WITH_GOOGLE',
  SIGN_IN_WITH_FACEBOOK: 'SIGN_IN_WITH_FACEBOOK',

  SIGN_IN_WITH_EMAIL: 'SIGN_IN_WITH_EMAIL',
  SIGN_IN_WITH_EMAIL_SUCCESS: 'SIGN_IN_WITH_EMAIL_SUCCESS',
  SIGN_IN_WITH_EMAIL_FAIL: 'SIGN_IN_WITH_EMAIL_FAIL',

  SIGN_UP_WITH_EMAIL: 'SIGN_UP_WITH_EMAIL',
  SIGN_UP_WITH_EMAIL_SUCCESS: 'SIGN_UP_WITH_EMAIL_SUCCESS',
  SIGN_UP_WITH_EMAIL_FAIL: 'SIGN_UP_WITH_EMAIL_FAIL',

  SEND_EMAIL_VERIFICATION: 'SEND_EMAIL_VERIFICATION',
  SEND_EMAIL_VERIFICATION_SUCCESS: 'SEND_EMAIL_VERIFICATION_SUCCESS',
  SEND_EMAIL_VERIFICATION_FAIL: 'SEND_EMAIL_VERIFICATION_FAIL',

  SEND_PASSWORD_RESET_EMAIL: 'SEND_PASSWORD_RESET_EMAIL',
  SEND_PASSWORD_RESET_EMAIL_SUCCESS: 'SEND_PASSWORD_RESET_EMAIL_SUCCESS',
  SEND_PASSWORD_RESET_EMAIL_FAIL: 'SEND_PASSWORD_RESET_EMAIL_FAIL',

  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_OUT_USER_FAIL: 'SIGN_OUT_USER_FAIL',

  FETCH_ALL_POSTS: 'FETCH_ALL_POSTS',
  FETCH_ALL_POSTS_SUCCESS: 'FETCH_ALL_POSTS_SUCCESS',
  FETCH_ALL_POSTS_FAIL: 'FETCH_ALL_POSTS_FAIL',

  FETCH_POST: 'FETCH_POST',
  FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
  FETCH_POST_FAIL: 'FETCH_POST_FAIL',

  CREATE_POST: 'CREATE_POST',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAIL: 'CREATE_POST_FAIL',

  EDIT_POST: 'EDIT_POST',
  EDIT_POST_SUCCESS: 'EDIT_POST_SUCCESS',
  EDIT_POST_FAIL: 'EDIT_POST_FAIL',

  FETCH_MY_POSTS_SUCCESS: 'FETCH_MY_POSTS_SUCCESS',
  FETCH_MY_POSTS_FAIL: 'FETCH_MY_POSTS_FAIL',

  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAIL: 'DELETE_POST_FAIL',

  DELETE_POSTS_SUCCESS: 'DELETE_POSTS_SUCCESS',
  DELETE_POSTS_FAIL: 'DELETE_POSTS_FAIL',

  INCREASE_LIMIT_COUNT_OF_GRID: 'INCREASE_LIMIT_COUNT_OF_GRID',

  SELECT_MY_POSTS: 'SELECT_MY_POSTS',
  SELECT_MY_POSTS_ALL: 'SELECT_MY_POSTS_ALL',
  SELECT_MY_POSTS_RESET: 'SELECT_MY_POSTS_RESET',

  CHANGE_FILTER_CRITERION_SUCCESS: 'CHANGE_FILTER_CRITERION_SUCCESS',

  CLEAR_FILTER_CRITERION_SUCCESS: 'CLEAR_FILTER_CRITERION_SUCCESS',

  GET_FILTER_SELECTOR_RANGE_SUCCESS: 'GET_FILTER_SELECTOR_RANGE_SUCCESS',
  GET_FILTER_SELECTOR_RANGE_FAIL: 'GET_FILTER_SELECTOR_RANGE_FAIL',

  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAIL: 'CREATE_COMMENT_FAIL',

  DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
  DELETE_COMMENT_FAIL: 'DELETE_COMMENT_FAIL',

  TOGGLE_LIKE_SUCCESS: 'TOGGLE_LIKE_SUCCESS',
  TOGGLE_LIKE_FAIL: 'TOGGLE_LIKE_FAIL',

  REDUCE_SNACKBAR_QUEUE: 'REDUCE_SNACKBAR_QUEUE',

  ADD_SNACKBAR_QUEUE: 'ADD_SNACKBAR_QUEUE',

  START_PROGRESS: 'START_PROGRESS',
  FINISH_PROGRESS: 'FINISH_PROGRESS',

  USER_REDIRECTED: 'USER_REDIRECTED',

  SAVE_MAP_ZOOM_AND_CENTER: 'SAVE_MAP_ZOOM_AND_CENTER',

  UPDATE_MAP_ZOOM_AND_CENTER_SUCCESS: 'UPDATE_MAP_ZOOM_AND_CENTER_SUCCESS',
  UPDATE_MAP_ZOOM_AND_CENTER_FAIL: 'UPDATE_MAP_ZOOM_AND_CENTER_FAIL',

  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
};
