export default {
  FETCH_ALL_POSTS_SUCCESS: 'FETCH_ALL_POSTS_SUCCESS',
  FETCH_ALL_POSTS_FAIL: 'FETCH_ALL_POSTS_FAIL',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAIL: 'CREATE_POST_FAIL',
  FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
  FETCH_USER_INFO_FAIL: 'FETCH_USER_INFO_FAIL',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAIL: 'UPDATE_USER_INFO_FAIL',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAIL: 'DELETE_USER_FAIL',
};
